# Real World Dataset

In [1]:
## read_csv() ---> this function reads the content from csv file in Pandas so that we can perform operations on the data or we can perform effective analysis.

In [2]:
import pandas as pd
import numpy as np

In [4]:
pd.read_csv("C:/Users/TIRTHESH/Downloads/archive/youtube_2025_dataset_202504061614.csv")

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [6]:
df=pd.read_csv('youtube_2025_dataset.csv')

In [7]:
df

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [8]:
# Dataframe ---> Combination of Multiple Series (Column).

In [9]:
## squeeze() ---> Squeeze parameter make sure that the data is in series format.

In [11]:
type(pd.read_csv("youtube_one.csv"))

pandas.DataFrame

In [20]:
df = pd.read_csv("youtube_one.csv").squeeze("columns")

In [14]:
type(df)

pandas.Series

In [22]:
dataframe = pd.read_csv("youtube_two.csv",index_col="Channel Name").squeeze("columns")

In [23]:
dataframe

Channel Name
Smith-Ross Labs                 68
Sandoval PLC Hub               128
Jones, Moore and Ho Network    282
Mitchell-Hooper Labs           302
Wilson LLC Studios             129
                              ...
Flores-Daniel Studios          106
Spencer and Sons Studios       130
Obrien-Roberts Studios         179
King Ltd Hub                   182
Henry Ltd Studios               92
Name: Total Videos, Length: 5000, dtype: int64

In [ ]:
# attributes of series
## 1. values ---> representing onlly the values of the given series.
## 2. index ---> representing the index of the series
## 3. dtype ---> representing the data type of the series
## 4. name ---> representing the name of the series
## 5. size ---> Provides the idea about the total no. of rows in the series.
## 6. shape ---> Idea about rows and columns.
## 7. ndim ---> Idea about the dimension of the series.
## 8. is_unique ---> True if the index is unique else False

In [24]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [25]:
dataframe.index

Index(['Smith-Ross Labs', 'Sandoval PLC Hub', 'Jones, Moore and Ho Network',
       'Mitchell-Hooper Labs', 'Wilson LLC Studios', 'Myers Ltd Network',
       'Huber Inc Network', 'Baxter-Collins Studios', 'Morrow-Abbott Hub',
       'Jackson Group Network',
       ...
       'Cole-Sharp Labs', 'Sherman, Mcgee and Phillips Studios',
       'Baker-Hill Hub', 'Francis, Davis and Jones Network',
       'Whitaker, Horn and Escobar Labs', 'Flores-Daniel Studios',
       'Spencer and Sons Studios', 'Obrien-Roberts Studios', 'King Ltd Hub',
       'Henry Ltd Studios'],
      dtype='str', name='Channel Name', length=5000)

In [26]:
dataframe.dtype

dtype('int64')

In [27]:
dataframe.name

'Total Videos'

In [28]:
dataframe = dataframe.astype('int32')

In [29]:
dataframe.dtype

dtype('int32')

In [30]:
dataframe.size

5000

In [32]:
dataframe.shape

(5000,)

In [34]:
dataframe.ndim

1

In [36]:
dataframe.is_unique

False

In [ ]:
## Series Method

## 1. head() ---> Provides top preview of data as the top 5 rows of the dataframe or series.
## 2. tail() ---> Provides bottom preview of data as the bottom 5 rows of the dataframe or series.

In [39]:
dataframe.head(10)

Channel Name
Smith-Ross Labs                 68
Sandoval PLC Hub               128
Jones, Moore and Ho Network    282
Mitchell-Hooper Labs           302
Wilson LLC Studios             129
Myers Ltd Network               98
Huber Inc Network              494
Baxter-Collins Studios         133
Morrow-Abbott Hub              316
Jackson Group Network          140
Name: Total Videos, dtype: int32

In [40]:
dataframe.tail(8)

Channel Name
Baker-Hill Hub                      261
Francis, Davis and Jones Network    126
Whitaker, Horn and Escobar Labs     231
Flores-Daniel Studios               106
Spencer and Sons Studios            130
Obrien-Roberts Studios              179
King Ltd Hub                        182
Henry Ltd Studios                    92
Name: Total Videos, dtype: int32